name: Laravel Sail CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: |
        docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd):/var/www/html" \
          -w /var/www/html \
          laravelsail/php84-composer:latest \
          composer install --ignore-platform-reqs

    - name: Start Sail
      run: ./vendor/bin/sail up -d

    - name: Generate Application Key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run Migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Seed Database
      run: ./vendor/bin/sail artisan db:seed --force

    - name: Install NPM Dependencies
      run: ./vendor/bin/sail npm install

    - name: Build Frontend
      run: ./vendor/bin/sail npm run build

    - name: Run Tests
      run: ./vendor/bin/sail test
